export type IconTypes =
  | 'share'
  | 'add-cross'
  | 'check-case'
  | 'error'
  | 'success'
  | 'dot-menu'
  | 'password-show'
  | 'password-hide'
  | 'logo'
  | 'github'
  | 'telegram'
  | 'linkedin'
  | 'rss'
  | 'edit';
